<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Sample Receipt</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 12px;
            color: #111827;
            margin: 28px;
        }
        .header {
            border-bottom: 2px solid #0f172a;
            padding-bottom: 10px;
            margin-bottom: 18px;
        }
        .title {
            font-size: 20px;
            font-weight: 700;
            margin: 0;
        }
        .subtitle {
            margin: 4px 0 0 0;
            color: #334155;
        }
        .box {
            border: 1px solid #cbd5e1;
            border-radius: 6px;
            padding: 14px;
            margin-bottom: 14px;
        }
        .row {
            margin-bottom: 8px;
        }
        .label {
            display: inline-block;
            width: 120px;
            color: #334155;
            font-weight: 600;
        }
        .amount {
            font-size: 18px;
            font-weight: 700;
            color: #0f172a;
        }
        .footer {
            margin-top: 24px;
            color: #475569;
            font-size: 11px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">Sample Receipt</h1>
        <p class="subtitle">Demo template for receipts/finiquitos (no financial logic)</p>
    </div>

    <div class="box">
        <div class="row"><span class="label">Folio:</span> {{ $receipt['folio'] }}</div>
        <div class="row"><span class="label">Nombre:</span> {{ $receipt['nombre'] }}</div>
        <div class="row"><span class="label">Unidad:</span> {{ $receipt['unidad'] }}</div>
        <div class="row"><span class="label">Fecha:</span> {{ $receipt['fecha'] }}</div>
    </div>

    <div class="box">
        <div class="row"><span class="label">Monto:</span> <span class="amount">${{ number_format($receipt['monto'], 2) }} MXN</span></div>
    </div>

    <p class="footer">
        Generated by inmo-admin PDF sample route.
    </p>
</body>
</html>
